### ISSUE TITLE
detectexit.sh sometimes not working 

### ISSUE THREAD

**Issue by nosaj9** [BlackrazorS2/HACS200-Research#5]

**Comment by lg4492** [comment]
Looks like the problem was that attackers sometimes exited before getting in the container, and the MITM printed out the line "Attacker closed the connection" instead of "Attacker closed connection".
Fix: changed line that detectexit.sh checks for to "Attacker closed ".

**Comment by nosaj9** [comment]
This could have to do with MITM outputting the closed message too fast and the version of the script only checked the last five lines of the file. Changed it to check the entire file because each file only represents one session.
