### ISSUE TITLE
Attackers who try to connect as root are not getting in

### ISSUE THREAD

**Issue by lg4492** [BlackrazorS2/HACS200-Research#8]
Attackers who try to log in as root fail to log in. ([example](https://github.com/BlackrazorS2/HACS200-Research/blob/c89d7c95c51002ed4045000aceccf368d18a4155/Data%20Backups/2022-10-21-0842_DATABASE_1_log)). Might need to change MITM settings or something.

**Comment by Kaidriver** [comment]
Issue resolved by changing PermitRootLogin flag to yes in container
